# Generated by Django 3.1.6 on 2021-02-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
