# Generated by Django 3.1.6 on 2021-02-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Art', 'Art'), ('Animal', 'Animal'), ('IT', 'IT'), ('News', 'News'), ('Sport', 'Sport'), ('Other', 'Other')], max_length=300),
        ),
    ]
