# Generated by Django 3.1.6 on 2021-02-10 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_imagefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFile',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
