# Generated by Django 3.1.6 on 2021-02-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0008_auto_20210210_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300, unique=True)),
                ('category', models.CharField(choices=[('Art', 'Art'), ('Animal', 'Animal'), ('IT', 'IT'), ('News', 'News'), ('Sport', 'Sport'), ('Other', 'Other')], max_length=300)),
                ('image', models.ImageField(upload_to='images')),
                ('content', models.TextField()),
            ],
        ),
    ]
